//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Membership.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceResponse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResponse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Membership.Service.Resources.ServiceResponse", typeof(ServiceResponse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_ACTIVATED.
        /// </summary>
        public static string ACCOUNT_ACTIVATED {
            get {
                return ResourceManager.GetString("ACCOUNT_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_BLOCKED.
        /// </summary>
        public static string ACCOUNT_BLOCKED {
            get {
                return ResourceManager.GetString("ACCOUNT_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_DISABLE.
        /// </summary>
        public static string ACCOUNT_DISABLE {
            get {
                return ResourceManager.GetString("ACCOUNT_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_EMAIL_NOT_FOUND.
        /// </summary>
        public static string ACCOUNT_EMAIL_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_EMAIL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_BLOCKED.
        /// </summary>
        public static string API_ACCOUNT_BLOCKED {
            get {
                return ResourceManager.GetString("API_ACCOUNT_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_DISABLED.
        /// </summary>
        public static string API_ACCOUNT_DISABLED {
            get {
                return ResourceManager.GetString("API_ACCOUNT_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL_ALREADY_REGISTERED.
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL_IS_SUITABLE.
        /// </summary>
        public static string EMAIL_IS_SUITABLE {
            get {
                return ResourceManager.GetString("EMAIL_IS_SUITABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNAL_ERROR.
        /// </summary>
        public static string INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_ADDRESS_CREATE_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_CREATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_CREATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_ADDRESS_DELETE_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_DELETE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_DELETE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_ADDRESS_QUERY_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_QUERY_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_QUERY_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_ADDRESS_UPDATE_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_UPDATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_UPDATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_BLOCK_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_BLOCK_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_BLOCK_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_CONTACT_CREATE_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_CONTACT_CREATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CONTACT_CREATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_CONTACT_DELETE_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_CONTACT_DELETE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CONTACT_DELETE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_CONTACT_QUERY_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_CONTACT_QUERY_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CONTACT_QUERY_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_CONTACT_UPDATE_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_CONTACT_UPDATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CONTACT_UPDATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_CREATE_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_CREATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CREATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_DELETE_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_DELETE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_DELETE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_QUERY_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_QUERY_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_QUERY_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_UNBLOCK_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_UNBLOCK_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_UNBLOCK_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ACCOUNT_UPDATE_REQUEST.
        /// </summary>
        public static string INVALID_ACCOUNT_UPDATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_UPDATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_API_KEY.
        /// </summary>
        public static string INVALID_API_KEY {
            get {
                return ResourceManager.GetString("INVALID_API_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_AUTH_REQUEST.
        /// </summary>
        public static string INVALID_AUTH_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_AUTH_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CHECK_EMAIL_REQUEST.
        /// </summary>
        public static string INVALID_CHECK_EMAIL_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_CHECK_EMAIL_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_INPUT_ERROR.
        /// </summary>
        public static string INVALID_INPUT_ERROR {
            get {
                return ResourceManager.GetString("INVALID_INPUT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_IP_ADDRESS.
        /// </summary>
        public static string INVALID_IP_ADDRESS {
            get {
                return ResourceManager.GetString("INVALID_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_PASSWORD_CHANGE_REQUEST.
        /// </summary>
        public static string INVALID_PASSWORD_CHANGE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD_CHANGE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_REQUEST_HEADER.
        /// </summary>
        public static string INVALID_REQUEST_HEADER {
            get {
                return ResourceManager.GetString("INVALID_REQUEST_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_REQUEST_HEADER_TOKEN.
        /// </summary>
        public static string INVALID_REQUEST_HEADER_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_REQUEST_HEADER_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_TOKEN.
        /// </summary>
        public static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_CHANGED.
        /// </summary>
        public static string PASSWORD_CHANGED {
            get {
                return ResourceManager.GetString("PASSWORD_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_NOT_CHANGED.
        /// </summary>
        public static string PASSWORD_NOT_CHANGED {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_NOT_MISMATCH.
        /// </summary>
        public static string PASSWORD_NOT_MISMATCH {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOURCE_ALREADY_EXIST.
        /// </summary>
        public static string RESOURCE_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("RESOURCE_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOURCE_DELETED.
        /// </summary>
        public static string RESOURCE_DELETED {
            get {
                return ResourceManager.GetString("RESOURCE_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOURCE_INSERTED.
        /// </summary>
        public static string RESOURCE_INSERTED {
            get {
                return ResourceManager.GetString("RESOURCE_INSERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOURCE_NOT_FOUND.
        /// </summary>
        public static string RESOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOURCE_UPDATED.
        /// </summary>
        public static string RESOURCE_UPDATED {
            get {
                return ResourceManager.GetString("RESOURCE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED.
        /// </summary>
        public static string SERVICE_STATUS_FAILED {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT_ERROR.
        /// </summary>
        public static string SERVICE_STATUS_INPUT_ERROR {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_INPUT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        public static string SERVICE_STATUS_SUCCESS {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOO_MANY_REQUESTS.
        /// </summary>
        public static string TOO_MANY_REQUESTS {
            get {
                return ResourceManager.GetString("TOO_MANY_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRONG_ACCOUNT_PASSWORD.
        /// </summary>
        public static string WRONG_ACCOUNT_PASSWORD {
            get {
                return ResourceManager.GetString("WRONG_ACCOUNT_PASSWORD", resourceCulture);
            }
        }
    }
}
