//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Membership.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceResponseMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResponseMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Membership.Service.Resources.ServiceResponseMessage", typeof(ServiceResponseMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap aktive edildi..
        /// </summary>
        public static string ACCOUNT_ACTIVATED {
            get {
                return ResourceManager.GetString("ACCOUNT_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap bloklandı..
        /// </summary>
        public static string ACCOUNT_BLOCKED {
            get {
                return ResourceManager.GetString("ACCOUNT_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap aktif değil.
        /// </summary>
        public static string ACCOUNT_DISABLE {
            get {
                return ResourceManager.GetString("ACCOUNT_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresi bulunamadı..
        /// </summary>
        public static string ACCOUNT_EMAIL_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_EMAIL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api hesabı bloklandı..
        /// </summary>
        public static string API_ACCOUNT_BLOCKED {
            get {
                return ResourceManager.GetString("API_ACCOUNT_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api kullanıcı hesabı aktif değil..
        /// </summary>
        public static string API_ACCOUNT_DISABLED {
            get {
                return ResourceManager.GetString("API_ACCOUNT_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresi önceden kayıt edilmiş..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email kayıt için uygun..
        /// </summary>
        public static string EMAIL_IS_SUITABLE {
            get {
                return ResourceManager.GetString("EMAIL_IS_SUITABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel hata..
        /// </summary>
        public static string INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap AccountType alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_ACCOUNT_TYPE {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ACCOUNT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap adres alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_ADDRESS {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap adres şehir kodu alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_CITY_ID {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_CITY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap adres ülke kodu alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_COUNTRY_ID {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_COUNTRY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap adresi yaratma isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_CREATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_CREATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap adresi silme isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_DELETE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_DELETE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap adres semt kodu alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_DISTRICT_ID {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_DISTRICT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap adresi sorgulama isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_QUERY_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_QUERY_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap adresi güncelleme isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_ADDRESS_UPDATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ADDRESS_UPDATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap alternatif email alanı..
        /// </summary>
        public static string INVALID_ACCOUNT_ALTERNATIVE_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ALTERNATIVE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap ApplicationId alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_APPLICATION_ID {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_APPLICATION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap durumu değiştirme isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_BLOCK_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_BLOCK_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz kullanıcı kodu.
        /// </summary>
        public static string INVALID_ACCOUNT_CODE {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap kontak kişi bilgisi.
        /// </summary>
        public static string INVALID_ACCOUNT_CONTACT_CONTACT_NAME {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CONTACT_CONTACT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap kontak bilgisi yaratma isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_CONTACT_CREATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CONTACT_CREATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap kontak bilgisi silme isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_CONTACT_DELETE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CONTACT_DELETE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap kontak bilgisi sorgulama isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_CONTACT_QUERY_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CONTACT_QUERY_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap kontak bilgisi güncelleme isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_CONTACT_UPDATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CONTACT_UPDATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap yaratma isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_CREATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_CREATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap silme isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_DELETE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_DELETE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap Email alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap cinsiyet alanı..
        /// </summary>
        public static string INVALID_ACCOUNT_GENDER {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap gsm alanı..
        /// </summary>
        public static string INVALID_ACCOUNT_GSM {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap kimlik numarası alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_IDENTITY_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_IDENTITY_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap Name alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_NAME {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap Password alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap sorgulama isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_QUERY_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_QUERY_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap risk seviyesi alanı..
        /// </summary>
        public static string INVALID_ACCOUNT_RISK_LEVEL {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_RISK_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap Status alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_STATUS {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap Surname alanı.
        /// </summary>
        public static string INVALID_ACCOUNT_SURNAME {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap durumu değiştirme isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_UNBLOCK_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_UNBLOCK_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz hesap güncelleme isteği..
        /// </summary>
        public static string INVALID_ACCOUNT_UPDATE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_UPDATE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz adres kodu.
        /// </summary>
        public static string INVALID_ADDRESS_CODE {
            get {
                return ResourceManager.GetString("INVALID_ADDRESS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz ApiKey..
        /// </summary>
        public static string INVALID_API_KEY {
            get {
                return ResourceManager.GetString("INVALID_API_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz kimlik doğrulama isteği..
        /// </summary>
        public static string INVALID_AUTH_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_AUTH_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz email sorgulama isteği..
        /// </summary>
        public static string INVALID_CHECK_EMAIL_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_CHECK_EMAIL_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz kontak kodu.
        /// </summary>
        public static string INVALID_CONTACT_CODE {
            get {
                return ResourceManager.GetString("INVALID_CONTACT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz email..
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz ip adresinden istek geliyor..
        /// </summary>
        public static string INVALID_IP_ADDRESS {
            get {
                return ResourceManager.GetString("INVALID_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz şifre.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz şifre değiştime isteği..
        /// </summary>
        public static string INVALID_PASSWORD_CHANGE_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD_CHANGE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz istek başlık bilgisi. Request Header içinde X-MEMBERSHIP-APIKEY ve SECRET-KEY parametrelerini kontrol ediniz..
        /// </summary>
        public static string INVALID_REQUEST_HEADER {
            get {
                return ResourceManager.GetString("INVALID_REQUEST_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz istek başlık bilgisi. Request Header içinde TOKEN parametresini kontrol ediniz..
        /// </summary>
        public static string INVALID_REQUEST_HEADER_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_REQUEST_HEADER_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz token..
        /// </summary>
        public static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eski ve yeni şifre farklı olmalı..
        /// </summary>
        public static string OLD_AND_NEW_PASSWORD_MUST_BE_DIFFERENT {
            get {
                return ResourceManager.GetString("OLD_AND_NEW_PASSWORD_MUST_BE_DIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre değiştirildi..
        /// </summary>
        public static string PASSWORD_CHANGED {
            get {
                return ResourceManager.GetString("PASSWORD_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre değiştirilemedi..
        /// </summary>
        public static string PASSWORD_NOT_CHANGED {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre bilgisi eşleşmiyor..
        /// </summary>
        public static string PASSWORD_NOT_MISMATCH {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı değere sahip kayıt var..
        /// </summary>
        public static string RESOURCE_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("RESOURCE_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt silindi..
        /// </summary>
        public static string RESOURCE_DELETED {
            get {
                return ResourceManager.GetString("RESOURCE_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt eklendi..
        /// </summary>
        public static string RESOURCE_INSERTED {
            get {
                return ResourceManager.GetString("RESOURCE_INSERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı..
        /// </summary>
        public static string RESOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt güncellendi..
        /// </summary>
        public static string RESOURCE_UPDATED {
            get {
                return ResourceManager.GetString("RESOURCE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çok fazla sayıda istek geliyor.
        ///Rate Limit aşıldı..
        /// </summary>
        public static string TOO_MANY_REQUESTS {
            get {
                return ResourceManager.GetString("TOO_MANY_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı şifre..
        /// </summary>
        public static string WRONG_ACCOUNT_PASSWORD {
            get {
                return ResourceManager.GetString("WRONG_ACCOUNT_PASSWORD", resourceCulture);
            }
        }
    }
}
