//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Membership.CitizenService.CitizenService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CitizenType", Namespace="http://schemas.datacontract.org/2004/07/nish.service")]
    [System.SerializableAttribute()]
    public partial class CitizenType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CitizenService.ICitizenService")]
    public interface ICitizenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICitizenService/GetCitizenNameInfo", ReplyAction="http://tempuri.org/ICitizenService/GetCitizenNameInfoResponse")]
        Membership.CitizenService.CitizenService.CitizenType GetCitizenNameInfo(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICitizenService/GetCitizenNameInfo", ReplyAction="http://tempuri.org/ICitizenService/GetCitizenNameInfoResponse")]
        System.Threading.Tasks.Task<Membership.CitizenService.CitizenService.CitizenType> GetCitizenNameInfoAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICitizenServiceChannel : Membership.CitizenService.CitizenService.ICitizenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CitizenServiceClient : System.ServiceModel.ClientBase<Membership.CitizenService.CitizenService.ICitizenService>, Membership.CitizenService.CitizenService.ICitizenService {
        
        public CitizenServiceClient() {
        }
        
        public CitizenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CitizenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CitizenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CitizenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Membership.CitizenService.CitizenService.CitizenType GetCitizenNameInfo(string data) {
            return base.Channel.GetCitizenNameInfo(data);
        }
        
        public System.Threading.Tasks.Task<Membership.CitizenService.CitizenService.CitizenType> GetCitizenNameInfoAsync(string data) {
            return base.Channel.GetCitizenNameInfoAsync(data);
        }
    }
}
